version: "3.9"
services: 
  app:
    container_name: app
    build: ./infra/php
    volumes:
      - ./backend:/work
  
  web:
    container_name: nginx
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  db:
    container_name: mysql
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    ports:
        - "1025:1025"
        - "8025:8025"

volumes:
  db-store: